<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXfJWDSp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXfJWDSp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXfJWDSp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXfJWDSp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXfJWDSp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XfJWDSp',
    'container.build_id' => '407a2eda',
    'container.build_time' => 1646330540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXfJWDSp');
